name: pre-commit

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set execute permission
        run: chmod +x ./update_README.sh

      - name: Run pre-commit script
        run: ./update_README.sh

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Apply pre-commit changes"
