name: pre-commit

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Get original commit message
        id: get_message
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

      - name: Check commit message
        id: check_message
        run: |
          if [[ "${{ steps.get_message.outputs.message }}" == Time* ]]; then
            echo "should_run=true" >> $GITHUB_ENV
          else
            echo "should_run=false" >> $GITHUB_ENV
          fi

      - name: Set execute permission
        if: env.should_run == 'true'
        run: chmod +x ./update_README.sh

      - name: Run pre-commit script
        if: env.should_run == 'true'
        run: ./update_README.sh

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: env.should_run == 'true'
        with:
          commit_message: "${{ steps.get_message.outputs.message }}"
